import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import AppProvider from './app-provider';
import { cookies } from 'next/headers';
import SlideSession from '@/components/slide-session';
import accountApiRequest from '@/apiRequest/account';
import { AccountResType } from '@/schemaValidations/account.schema';

const roboto = Roboto({ subsets: ['vietnamese'], weight: ['100', '300'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');
  console.log('rootLayout', cookieStore.get('sessionToken'));
  let user: AccountResType['data'] | null = null;
  if (sessionToken) {
    const result = await accountApiRequest.me(sessionToken.value);
    user = result.payload.data;
  }
  console.log(user);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider user={user} initialSessionToken={sessionToken?.value}>
            <Header user={user} />
            {children}
            <SlideSession />
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
